<!DOCTYPE html>
<script>
"use strict";

class HttpError extends Error {
  constructor(response) {
    super(`${response.status} for ${response.url}`);
    this.name = 'HttpError';
    this.response = response;
  }
}

async function loadJson(url) {
  const response = await fetch(url);

  if (response.status == 200) {
    return await response.json();
  } else {
    throw new HttpError(response);
  }
}

// Pide nombres hasta que github devuelve un usuario v√°lido
async function demoGithubUser() {
  let name = prompt("Ingrese un nombre:", "iliakan");

  try {
    const user = await loadJson(`https://api.github.com/users/${name}`);
    alert(`Nombre completo: ${user.name}.`);
    return user;
  } catch (err) {
    if (err instanceof HttpError && err.response.status == 404) {
      alert("No existe tal usuario, por favor reingrese.");
      return await demoGithubUser();
    } else {
      throw err;
    }
  }
}

demoGithubUser();
</script>